[package]
name = "racy"
version = "0.1.0"
edition = "2018"

description = "RacyCell"
categories = ["no-std"]

[dependencies]
const-default = { version = "^0.3.0", optional = true }

[features]
unstable = []
